// Derived from WGER API muscle/equipment data seeded into exercises table
export const MUSCLE_GROUPS = [
  "Anterior deltoid",
  "Biceps brachii",
  "Brachialis",
  "Erector spinae",
  "Gastrocnemius",
  "Gluteus maximus",
  "Hamstrings",
  "Lateral deltoid",
  "Latissimus dorsi",
  "Pectoralis major",
  "Posterior deltoid",
  "Quadriceps",
  "Rectus abdominis",
  "Rhomboids",
  "Soleus",
  "Triceps brachii",
] as const;

export const EQUIPMENT_TYPES = [
  "Barbell",
  "Bench",
  "Body weight",
  "Cable machine",
  "Calf raise machine",
  "Dip bars",
  "Dumbbell",
  "Dumbbells",
  "Incline Bench",
  "Leg curl machine",
  "Leg extension machine",
  "Leg press machine",
  "Pull-up bar",
  "Squat rack",
] as const;
