// Derived from the reviewed exercise catalog seeded into exercises table
export const MUSCLE_GROUPS = [
  "Adductors",
  "Anterior deltoid",
  "Biceps brachii",
  "Brachialis",
  "Erector spinae",
  "Forearms",
  "Gastrocnemius",
  "Gluteus maximus",
  "Gluteus medius",
  "Hamstrings",
  "Lateral deltoid",
  "Latissimus dorsi",
  "Obliques",
  "Pectoralis major",
  "Posterior deltoid",
  "Quadriceps",
  "Rectus abdominis",
  "Rhomboids",
  "Soleus",
  "Trapezius",
  "Triceps brachii",
] as const;

export const EQUIPMENT_TYPES = [
  "Ab wheel",
  "Assisted pull-up machine",
  "Back extension bench",
  "Barbell",
  "Bench",
  "Body weight",
  "Box",
  "Cable machine",
  "Calf raise machine",
  "Chest press machine",
  "Decline bench",
  "Dip bars",
  "Dumbbell",
  "Dumbbells",
  "EZ-bar",
  "Glute kickback machine",
  "Hack squat machine",
  "Hip abduction machine",
  "Hip adduction machine",
  "Incline bench",
  "Kettlebell",
  "Leg extension machine",
  "Leg press machine",
  "Lying leg curl machine",
  "Mat",
  "Medicine ball",
  "Pec deck machine",
  "Preacher bench",
  "Pull-up bar",
  "Resistance band",
  "Reverse fly machine",
  "Rope attachment",
  "Row machine",
  "Seated calf raise machine",
  "Seated leg curl machine",
  "Shoulder press machine",
  "Smith machine",
  "Squat rack",
  "T-bar or landmine",
  "Triceps machine",
  "Triceps press machine",
  "Weight plate",
] as const;
